<a href="https://colab.research.google.com/github/samruddhi74/Numpy-basics/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([1,2,3])
print(f'type of a = {type(a)}, shape = {a.shape}, dim = {a.ndim}, size = {a.size}')


type of a = <class 'numpy.ndarray'>, shape = (3,), dim = 1, size = 3


In [ ]:
b = np.array([[1,2,3]])
print(f'shape = {b.shape}, size = {b.size}')

shape = (1, 3), size = 3


In [ ]:
c = np.array([[1,2,3], [4,5,6]])
print(f'shape = {c.shape}, size = {c.size}')

shape = (2, 3), size = 6


In [ ]:
d = np.array((1,2,3))
print(d)
print(d.shape)

[1 2 3]
(3,)


In [ ]:
e = np.array(((1,2,3),(4,5,6)))
print(e)
print(e.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
l = [1,2,3]
a = np.array([1,2,3])
print(type(l))
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a * 2)

[[2 4]
 [6 8]]


In [ ]:
a = np.array([])
print(a.shape)

b = np.zeros((2,2))
print(b)

c = np.ones((1,2))
print(c)

d = np.full((2,2), 8)
print(d)

e = np.eye(2)
print(e)

f = np.empty((2,2), dtype=int)
print(f)

g = np.empty((2,2))
print(g)

h = np.random.random((2,2))
print(h)

i = 5*np.random.random_sample((2,2))-5
print(i)

j = np.random.randn(2,2)
print(j)

k = 2.5*np.random.randn(2,2) + 3. # mu = 3 , var = 6.25
print(k)


(0,)
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[8 8]
 [8 8]]
[[1. 0.]
 [0. 1.]]
[[4607182418800017408                   0]
 [                  0 4607182418800017408]]
[[3.68335399e-315 0.00000000e+000]
 [2.37663529e-312             nan]]
[[0.75928584 0.96331494]
 [0.50121319 0.84941556]]
[[-1.7082555  -0.92550353]
 [-4.38463077 -3.17475689]]
[[-1.37216559 -0.17997068]
 [-0.00858047  1.70477437]]
[[5.38968332 4.53388718]
 [0.86070028 2.33385318]]


In [ ]:
a = ([1,2,3], [4,5,6])
b = np.ones_like(a)
print(b)
print(b.shape)

[[1 1 1]
 [1 1 1]]
(2, 3)


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0])
print(a[:,0])

[1 2 3]
[1 4]


In [ ]:
a = np.ones((1,2,3))
print(a[0].shape)
print(a[0,].shape)
print(a[0,:].shape)

print(a[0,1].shape)
print(a[0,1,:].shape)


(2, 3)
(2, 3)
(2, 3)
(3,)
(3,)


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[:,2])


[3 6 9]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
rows = [0,1,2]
cols = [0,1,0]
print(a[rows , cols])
# 1 2 3 row ka 1 2 1 column ka element

[1 4 5]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[np.arange(2),[0,1]])

[1 4]


In [ ]:
a = np.array([[1,2],[3,4]])
print(a[a>2])

[3 4]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array(['a','b','w','w','e'])
print(b[np.logical_and((a>1),(a<5))])

['b' 'w' 'w']


In [ ]:
x = np.array([1.0,2.3])
print(x.dtype)

float64


In [ ]:
x = x.astype(np.float32)
print(x.dtype)

float32


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(a+b)
print(np.add(a,b))

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]


In [ ]:
print(a-b)
print(np.subtract(a,b))

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [ ]:
print(a*b)
print(np.multiply(a,b))

[[ 1  4]
 [ 9 16]]
[[ 1  4]
 [ 9 16]]


In [ ]:
print(np.divide(a,b))
print(np.sqrt(a))

[[1. 1.]
 [1. 1.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
a = np.array([1,2,3])
l = [1,2,3]
print(a+a)
print(l+l)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [ ]:
norm = np.linalg.norm(a)

In [ ]:
print(norm) # square root of sum of square of all elements

3.7416573867739413


In [ ]:
# axis = 0 --> across rows lets say sum of each column
# axis = 1 --> across columns lets say sum of each row

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])
print(v.dot(w))
print(np.dot(v,w))
print(v@w)

219
219
219


In [ ]:
v = np.array([1,2,3])
vv = np.tile(v,(4,1))
print(vv)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
vh = np.tile(v,(1,4))
print(vh)

[[1 2 3 1 2 3 1 2 3 1 2 3]]


In [4]:
a = [1,2]
print(np.asarray(a))

[1 2]


In [6]:
np.random.seed(0)
a = np.random.randn()
np.random.seed(0)
print(a)
b = np.random.randn()
print(b)

1.764052345967664
1.764052345967664


In [7]:
a = np.asarray([1.0])
a.item()

1.0

In [10]:
print(np.random.choice(5,3, p = [0.1,0.2,0.3,0.4,0.0]))

[3 3 2]


In [11]:
a = np.arange(1,8,3)
print(a)

[1 4 7]


In [12]:
a = np.linspace(2,4,num = 5)
print(a)

[2.  2.5 3.  3.5 4. ]


In [19]:
a = np.array([[1,2,3],[4,5,6]])
a=a.reshape(3,-1)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
print(a.T)

[[1 3 5]
 [2 4 6]]


In [21]:
a = np.array([1,2,3])
print(a.T)
print(a[None,:])
print(a[:,None])

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [22]:
a = np.ones((1,2,3))
print(np.transpose(a,(1,0,2)).shape)

(2, 1, 3)


In [24]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.flatten())


[1 2 3 4 5 6]


In [25]:
print(np.sum(a,axis=0))

[ 9 12]


In [26]:
print(np.sum(a,axis=1))

[ 3  7 11]


In [27]:
print(np.mean(a,axis =0))

[3. 4.]


In [28]:
print(np.prod(a))

720


In [30]:
print(len(a))

3


In [31]:
print(np.max(a))

6


In [32]:
print(np.argmax(a))

5


In [33]:
a = np.array([0,1,2,3,4,5])
print(np.where(a<3, a, a*20))

[  0   1   2  60  80 100]


In [ ]:
# a.flatten(), np.ravel(a), np.reshape(a,-1) are all equivalent

In [34]:
a = np.array([[1,2,2],[3,4,4]])
print(np.unique(a))

[1 2 3 4]


In [36]:
a = np.array([1,2,3,4,4,5,5])
print(np.bincount(a))

[0 1 1 1 2 2]


In [ ]:
# np.exp(a)
# np.square(a)
# np.sqrt(a)
